name: Publish

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - run: curl -sSL -O https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
            - run: python get-poetry.py
            - run: echo "::add-path::$HOME/.poetry/bin"
            - run: poetry install
            - run: poetry run black . --check
            - run: poetry build
            - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
            - run: poetry publish
